image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: ZjJMtxL/w30vL64PZcWWx7Z4n/VBDueNa5cZAWJtsiUomrJQ1aDzf+dpUY0V6TO7K1ygfeIzdyTQHdR9TX8tPVl0zjTTQVyWxeQfeTjmuBkqBsEZUdBWmdOi7BvFsKck

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name mlref --icon icon.png --product-name QuestionAnswerer --product-version "0.0.1" --copyright "Copyright (c) 2022 AI Institute B.V. All rights reserved"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a mlref-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: mlref-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf mlref-macos.tar.gz -C dist mlref.app

  artifacts:
  - path: mlref-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf mlref-linux.tar.gz -C dist mlref

  artifacts:
  - path: mlref-linux.tar.gz

